typography_spectrum: 0.8783149593509734
color:
  brandStrength: 0.07023802469484508
  lightness: 0.6004385778214782
  saturation: 0.832626060815528
  rhythmicContrast: 0.143021629890427
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
opengraph:
  type: 'Window Furnishing '
  appId: Patel Blinds
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3641be66-4b53-4f7d-be35-f094c2334bc5.jpg
layout_spectrum: 0.4364866064861417
author:
  name: 'Ranjithkumar '
  email: kumard@live.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d9b2ae69-a3d2-4df1-b393-04d3f02609b9.png
name: Patel Blinds
